language: java
jdk:
  - openjdk8

#1
branches:
  only:
    - master

# Travis CI 서버의 Home
#2
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

#3
script: "./gradlew clean build"

#4
notifications:
  email:
    recipients:
      - lhy3180@naver.com